---
- name: Install mysql on db servers
  hosts: db
  become: yes
  gather_facts: false
  roles:
    - role: roles/buluma.mysql
      mysql_databases:
        - name: tooling
          encoding: utf8
          collation: utf8_bin
      mysql_users:
        - name: webaccess
          password: WebaPass
          priv: "tooling.*:ALL"
          update_password: on_create

  tasks:
    - include_role:
        name: buluma.mysql
        tasks_from: dbserver.yml

