---
- name: Install mysql on db servers
  hosts: db
  become: yes
  gather_facts: yes
  roles:
    - role: roles/mysqlRole
      mysql_databases:
        - name: tooling
          encoding: utf8
          collation: utf8_bin
      mysql_users:
        - name: webaccess
          password: WebaPass
          priv: "tooling.*:ALL"
          update_password: on_create
