---
- name: install mysql database servers
  hosts: db
  become: yes
  gather_facts: yes

  roles:
    - role: buluma.mysql
      mysql_databases:
        - name: tooling
          encoding: utf8
          collation: utf8_bin
      mysql_users:
        - name: weba
          password: WebPass
          priv: "tooling.*:ALL"
          update_password: on_create

  hosts: webservers
  become: true
  tasks:
    - include_role:
        name: buluma.mysql
        tasks_from: webdb.yml

