---
- hosts: db
  become: true

  vars:
    # MySQL
    mysql:
      enabled: true
      repo: "mysql"
      version: "8.0"
      service:
        state: "started"
        enabled: true
    # MySQL -> install
    mysql_install:
      enabled: true
    # MySQL -> config
    mysql_config:
      enabled: true
      file: "{{ mysql_const[ansible_os_family]['config_file']}}"
      src: "mysql_server.conf.j2"
      backup: false
      skip-grant-tables: false
      data:
        pid-file: "{{ mysql_const[ansible_os_family]['pid-file'] }}"
        socket: "{{ mysql_const[ansible_os_family]['socket'] }}"
        datadir: "{{ mysql_const[ansible_os_family]['datadir'] }}"
        log-error: "{{ mysql_const[ansible_os_family][mysql.repo]['log-error'] }}"
  
  tasks:
    - name: include role darexsu.mysql
      include_role: 
        name: darexsu.mysql
