[nfs]
172.31.32.82 ansible_ssh_user='ec2-user'

[webservers]
172.31.45.242 ansible_ssh_user='ec2-user'
172.31.40.87 ansible_ssh_user='ec2-user'

[db]
172.31.32.157 ansible_ssh_user='ec2-user' 

[lb]
172.31.40.176 ansible_ssh_user='ubuntu'