---
- name: update web, nfs and db servers
  hosts: webservers, nfs, db
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
    - name: ensure wireshark is at the latest version
      yum:
        name: wireshark
        state: latest

    - name: add backup directory
      file:
        path: ~/backup
        state: directory

    - name: create update file
      file:
        path: ~/backup/update
        state: touch

    - name: update timezone to Etc/UTC
        copy: content="Etc/UTC\n" dest=/etc/timezone owner=root group=root mode=0644
        register: timezone

    - name: reconfigure timezone data (if changed)
        shell: dpkg-reconfigure -f noninteractive tzdata
        when: timezone.changed

    - name: Transfer the webshell.sh script
      copy: src=webshell.sh dest=/home/backup mode=0777

    - name: Execute the webshell.sh script
      command: sh /home/backup/webshell.sh

- name: update LB server
  hosts: lb
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: Update apt repo
      apt: 
        update_cache: yes

    - name: ensure wireshark is at the latest version
      apt:
        name: wireshark
        state: latest

    - name: add backup directory
      file:
        path: ~/backup
        state: directory

    - name: create update file
      file:
        path: ~/backup/update
        state: touch

    - name: update timezone to Etc/UTC
        copy: content="Etc/UTC\n" dest=/etc/timezone owner=root group=root mode=0644
        register: timezone

    - name: reconfigure timezone data (if changed)
        shell: dpkg-reconfigure -f noninteractive tzdata
        when: timezone.changed

    - name: Transfer the webshell.sh script
      copy: src=webshell.sh dest=/home/backup mode=0777
      
    - name: Execute the webshell.sh script
      command: sh /home/backup/webshell.sh