---
# tasks file for mysql

- name: Import assert.yml
  import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: Install mysql
  ansible.builtin.package:
    name: "{{ mysql_packages }}"
    state: present
  notify:
    - Set root password
    - Systemctl daemon-reexec
