pipeline {
    agent any

    environment {
        ANSIBLE_CONFIG="${WORKSPACE}/deploy/ansible.cfg"
    }

    parameters {
      string(name: 'inventory', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configuration')
    }

    stages {
        stage('initial cleanup') {
            steps {
              dir("${WORKSPACE}") {
                deleteDir()
              }
            }
        }

        stage('SCM checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/stlng1/ansible-config.git'
            }
        }

        stage ('Prepare Ansible For Execution') {
            steps {
                sh 'echo ${WORKSPACE}' 
                sh 'sed -i "3 a roles_path=${WORKSPACE}/roles" ${WORKSPACE}/deploy/.ansible.cfg'  
            }
        }

        stage('Execute Ansible Playbook') {
            steps {
                ansiblePlaybook become: true, credentialsId: 'ubuntu-private-key', disableHostKeyChecking: true, installation: 'Ansible 2.13.5', inventory: 'inventory/${inventory}', playbook: 'playbooks/site.yml'
            }
        }

        stage ('Clean Workspace after build') {
            steps {
                cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenUnstable: true, deleteDirs: true)
            }
        }
    }
}

