---
# - name: Update hosts
#   become: true
#   lineinfile:
#     path: /etc/hosts
#     state: present
#     line: "{{ item }}"
#   with_items:
#   - '{{ web1 }} web1'
#   - '{{ web2 }} web2'

- name: Install nginx webserver
  become: true
  apt: name=nginx state=latest update_cache=true
  notify: restart nginx

- name: Copy configuration file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/lb.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: Edit config file
  lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: '(include\ \/etc\/nginx\/sites-enabled\/\*;)'
    line: '# \1'
    backrefs: yes
    state: present
  notify: restart nginx

# - name: configure nginx for loadbalancing
#   become: true
#   template:
#     src: ../templates/nginx.conf.j2
#     dest: "/etc/nginx/nginx.conf"
#   notify: reload nginx
