---
- name: Update hosts
  become: true
  lineinfile:
    path: /etc/hosts
    state: present
    line: "{{ item }}"
  with_items:
  - '{{ web1 }} web1'
  - '{{ web2 }} web2'

- name: Install nginx webserver
  become: true
  apt: name=nginx state=latest update_cache=true
  notify: restart nginx

- name: configure nginx for loadbalancing
  become: true
  template:
    src: ../templates/nginx.conf.j2
    dest: "/etc/nginx/nginx.conf"
  notify: reload nginx
