---
- hosts: all
  become: true

# pre_tasks:
# - name: "Make sure remote system is initialized correctly"
#   raw: 'ln -s /usr/bin/python3 /usr/bin/python'
#   register: set_symlink
#   failed_when: set_symlink.rc != 0 and set_symlink.rc != 1 

# - name: Include dynamic variables
#   import_playbook: ../static-assignments/common.yml
# - include: ../dynamic-assignments/env-vars.yml
#   tags:
#     - always

# - name: delete wireshack installation
#   import_playbook: ../static-assignments/common-del.yml

- name: Database server assignment
  import_playbook: ../static-assignments/db_servers.yml

- name: Webserver assignment
  import_playbook: ../static-assignments/webservers.yml

- name: webserver mysql-client assignment
  import_playbook: ../static-assignments/webdb-client.yml

- name: Loadbalancers assignment
  import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required
