---
- hosts: all
  become: true

# - name: Include dynamic variables
#   import_playbook: ../static-assignments/common.yml
# - include: ../dynamic-assignments/env-vars.yml
#   tags:
#     - always

# - name: delete wireshack installation
#   import_playbook: ../static-assignments/common-del.yml

# - name: artifactory assignment
#   import_playbook: ../static-assignments/artifactory.yml

- name: database server assignment
  import_playbook: ../static-assignments/db_servers.yml

- name: tooling assignment
  import_playbook: ../static-assignments/tooling.yml

- name: mysql-client assignment
  import_playbook: ../static-assignments/webdb-client.yml

- name: nginx assignment
  import_playbook: ../static-assignments/nginx.yml
  when: load_balancer_is_required

# - name: todo assignment
#   ansible.builtin.import_playbook: ../static-assignments/todo.yml

- name: sonarqube assignment
  ansible.builtin.import_playbook: ../static-assignments/sonarqube.yml